services:
  - docker

before_install:
  - docker build -t judrin/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true judrin/react-test npm test

after_success:
  - docker build -t judrin/multi-client ./client
  - docker build -t judrin/multi-nginx ./nginx_router
  - docker build -t judrin/multi-server ./server
  - docker build -t judrin/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push judrin/multi-client
  - docker push judrin/multi-nginx
  - docker push judrin/multi-server
  - docker push judrin/multi-worker
